# Site settings
title: Melissa Keizer's Blog & Portfolio
email: hi@melissakeizer.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio and blog of Melissa Keizer - a UI/UX designer, front-end developer and photographer from Bangor, Northern Ireland.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://melissakeizer.com" # the base hostname & protocol for your site

twitter: http://twitter.com/keizgoesboom
dribbble: https://dribbble.com/KeizGoesBoom
linkedin: https://www.linkedin.com/profile/view?id=364389896
flickr: http://flickr.com/photos/tinyspark_boom
exposure: https://melissakeizer.exposure.co/
instagram:  http://instagram.com/keizgoesboom
facebook: https://www.facebook.com/melissakeizerphotography/

# Build settings
markdown: kramdown
permalink: /journal/:title/
paginate: 5
paginate_path: "/journal/:num/"